### ISSUE TITLE
Discord Server Links Invalid

### ISSUE THREAD

**Issue by milkev** [Rynn-Lee/Rynn-Lee#1]
Hi, sorry I couldn't find any other way to say anything about this, but the discord links on the three minecraft mods you have on modrinth arent valid anymore.

**Comment by Rynn-Lee** [comment]
Hmm, weird. Discord said that the link will never expire 🤔.
Thank you for informing me, here's another invite link https://discord.gg/g2N8PGDDEv. I hope this one will never expire
